services:
  frontend:
    image: nginx
    container_name: frontend_cont
    volumes:
      - /adhamdockers/frontend:/usr/share/nginx/html
    ports:
      - "8808:80"


  backend:
    image: python:3.9-slim
    container_name: backend_cont
    volumes:
      - /adhamdockers/backend:/app
    working_dir: /app
    #to ensure that the container's working directory is /app—the same place where your Flask application (app.py) and other project files are located.
    ports:
      - "8809:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    command: >
      bash -c "
        pip install flask &&
        python3 app.py
      "
